# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /run/media/h3m/data/学习/项目/WebServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /run/media/h3m/data/学习/项目/WebServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/h3m/data/学习/项目/WebServer/CMakeFiles /run/media/h3m/data/学习/项目/WebServer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/h3m/data/学习/项目/WebServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WebServer

# Build rule for target.
WebServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WebServer
.PHONY : WebServer

# fast build rule for target.
WebServer/fast:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/build
.PHONY : WebServer/fast

# target to build an object file
Channel.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/Channel.o
.PHONY : Channel.o

# target to preprocess a source file
Channel.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/Channel.i
.PHONY : Channel.i

# target to generate assembly for a file
Channel.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/Channel.s
.PHONY : Channel.s

# target to build an object file
Epoll.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/Epoll.o
.PHONY : Epoll.o

# target to preprocess a source file
Epoll.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/Epoll.i
.PHONY : Epoll.i

# target to generate assembly for a file
Epoll.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/Epoll.s
.PHONY : Epoll.s

# target to build an object file
EventLoop.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/EventLoop.o
.PHONY : EventLoop.o

# target to preprocess a source file
EventLoop.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/EventLoop.i
.PHONY : EventLoop.i

# target to generate assembly for a file
EventLoop.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/EventLoop.s
.PHONY : EventLoop.s

# target to build an object file
EventLoopThread.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/EventLoopThread.o
.PHONY : EventLoopThread.o

# target to preprocess a source file
EventLoopThread.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/EventLoopThread.i
.PHONY : EventLoopThread.i

# target to generate assembly for a file
EventLoopThread.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/EventLoopThread.s
.PHONY : EventLoopThread.s

# target to build an object file
EventLoopThreadPool.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/EventLoopThreadPool.o
.PHONY : EventLoopThreadPool.o

# target to preprocess a source file
EventLoopThreadPool.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/EventLoopThreadPool.i
.PHONY : EventLoopThreadPool.i

# target to generate assembly for a file
EventLoopThreadPool.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/EventLoopThreadPool.s
.PHONY : EventLoopThreadPool.s

# target to build an object file
HttpData.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/HttpData.o
.PHONY : HttpData.o

# target to preprocess a source file
HttpData.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/HttpData.i
.PHONY : HttpData.i

# target to generate assembly for a file
HttpData.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/HttpData.s
.PHONY : HttpData.s

# target to build an object file
Main.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/Main.o
.PHONY : Main.o

# target to preprocess a source file
Main.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/Main.i
.PHONY : Main.i

# target to generate assembly for a file
Main.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/Main.s
.PHONY : Main.s

# target to build an object file
Server.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/Server.o
.PHONY : Server.o

# target to preprocess a source file
Server.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/Server.i
.PHONY : Server.i

# target to generate assembly for a file
Server.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/Server.s
.PHONY : Server.s

# target to build an object file
ThreadPool.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/ThreadPool.o
.PHONY : ThreadPool.o

# target to preprocess a source file
ThreadPool.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/ThreadPool.i
.PHONY : ThreadPool.i

# target to generate assembly for a file
ThreadPool.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/ThreadPool.s
.PHONY : ThreadPool.s

# target to build an object file
Timer.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/Timer.o
.PHONY : Timer.o

# target to preprocess a source file
Timer.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/Timer.i
.PHONY : Timer.i

# target to generate assembly for a file
Timer.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/Timer.s
.PHONY : Timer.s

# target to build an object file
Util.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/Util.o
.PHONY : Util.o

# target to preprocess a source file
Util.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/Util.i
.PHONY : Util.i

# target to generate assembly for a file
Util.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/Util.s
.PHONY : Util.s

# target to build an object file
base/AsyncLogging.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/AsyncLogging.o
.PHONY : base/AsyncLogging.o

# target to preprocess a source file
base/AsyncLogging.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/AsyncLogging.i
.PHONY : base/AsyncLogging.i

# target to generate assembly for a file
base/AsyncLogging.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/AsyncLogging.s
.PHONY : base/AsyncLogging.s

# target to build an object file
base/CountDownLatch.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/CountDownLatch.o
.PHONY : base/CountDownLatch.o

# target to preprocess a source file
base/CountDownLatch.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/CountDownLatch.i
.PHONY : base/CountDownLatch.i

# target to generate assembly for a file
base/CountDownLatch.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/CountDownLatch.s
.PHONY : base/CountDownLatch.s

# target to build an object file
base/FileUtil.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/FileUtil.o
.PHONY : base/FileUtil.o

# target to preprocess a source file
base/FileUtil.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/FileUtil.i
.PHONY : base/FileUtil.i

# target to generate assembly for a file
base/FileUtil.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/FileUtil.s
.PHONY : base/FileUtil.s

# target to build an object file
base/LogFile.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/LogFile.o
.PHONY : base/LogFile.o

# target to preprocess a source file
base/LogFile.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/LogFile.i
.PHONY : base/LogFile.i

# target to generate assembly for a file
base/LogFile.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/LogFile.s
.PHONY : base/LogFile.s

# target to build an object file
base/LogStream.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/LogStream.o
.PHONY : base/LogStream.o

# target to preprocess a source file
base/LogStream.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/LogStream.i
.PHONY : base/LogStream.i

# target to generate assembly for a file
base/LogStream.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/LogStream.s
.PHONY : base/LogStream.s

# target to build an object file
base/Logging.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/Logging.o
.PHONY : base/Logging.o

# target to preprocess a source file
base/Logging.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/Logging.i
.PHONY : base/Logging.i

# target to generate assembly for a file
base/Logging.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/Logging.s
.PHONY : base/Logging.s

# target to build an object file
base/Thread.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/Thread.o
.PHONY : base/Thread.o

# target to preprocess a source file
base/Thread.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/Thread.i
.PHONY : base/Thread.i

# target to generate assembly for a file
base/Thread.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/base/Thread.s
.PHONY : base/Thread.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... WebServer"
	@echo "... edit_cache"
	@echo "... Channel.o"
	@echo "... Channel.i"
	@echo "... Channel.s"
	@echo "... Epoll.o"
	@echo "... Epoll.i"
	@echo "... Epoll.s"
	@echo "... EventLoop.o"
	@echo "... EventLoop.i"
	@echo "... EventLoop.s"
	@echo "... EventLoopThread.o"
	@echo "... EventLoopThread.i"
	@echo "... EventLoopThread.s"
	@echo "... EventLoopThreadPool.o"
	@echo "... EventLoopThreadPool.i"
	@echo "... EventLoopThreadPool.s"
	@echo "... HttpData.o"
	@echo "... HttpData.i"
	@echo "... HttpData.s"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... Server.o"
	@echo "... Server.i"
	@echo "... Server.s"
	@echo "... ThreadPool.o"
	@echo "... ThreadPool.i"
	@echo "... ThreadPool.s"
	@echo "... Timer.o"
	@echo "... Timer.i"
	@echo "... Timer.s"
	@echo "... Util.o"
	@echo "... Util.i"
	@echo "... Util.s"
	@echo "... base/AsyncLogging.o"
	@echo "... base/AsyncLogging.i"
	@echo "... base/AsyncLogging.s"
	@echo "... base/CountDownLatch.o"
	@echo "... base/CountDownLatch.i"
	@echo "... base/CountDownLatch.s"
	@echo "... base/FileUtil.o"
	@echo "... base/FileUtil.i"
	@echo "... base/FileUtil.s"
	@echo "... base/LogFile.o"
	@echo "... base/LogFile.i"
	@echo "... base/LogFile.s"
	@echo "... base/LogStream.o"
	@echo "... base/LogStream.i"
	@echo "... base/LogStream.s"
	@echo "... base/Logging.o"
	@echo "... base/Logging.i"
	@echo "... base/Logging.s"
	@echo "... base/Thread.o"
	@echo "... base/Thread.i"
	@echo "... base/Thread.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

